name: norse
on: [push, pull_request]
#schedule:
    # * is a special character in YAML so you have to quote this string
   # - cron:  '*/30 5,17 * * *'
defaults:
  run:
    shell: bash -l {0}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        activate-environment: norse
        channels: defaults
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test conda install
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt