name: norse_conda_install
on: [push, pull_request]
defaults:
  run:
    shell: bash -l {0}

jobs:
  norse_test:
    name: norse conda install on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Hint: ubuntu-latest is 22.04/24.04, macos-latest is now ARM64 (M1/M2)
        os: ["ubuntu-latest", "macos-latest"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          channels: conda-forge, defaults
          auto-update-conda: true
          activate-environment: norse
          auto-activate-base: false

      - name: Install environment dependencies
        run: conda install python=3.9 numpy"<2.0" pandas rsync --yes
      
      - name: Install pip dependencies
        run: pip install "PyQt5>=5.15.3" "requests>=2.25.1" "paramiko>=2.7.2" openpyxl xlrd qtwidgets
      
      - name: Install setup.py
        run: pip install .
      
      - name: Check norse version
        run: norse --version
