name: norse_pip_install
on: [push, pull_request]
#schedule:
    # * is a special character in YAML so you have to quote this string
   # - cron:  '*/30 5,17 * * *'
defaults:
  run:
    shell: bash -l {0}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test pip install
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install setup.py
      run: python setup.py install
    - name: Check norse version
      run: norse --version